# Generated by Django 5.1.1 on 2024-11-14 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('subject', models.CharField(choices=[('accommodation_quote', 'accommodation_quote'), ('event_quote', 'event_quote'), ('lost_object', 'lost_object'), ('general_question', 'general_question'), ('complaint', 'complaint'), ('accommodation_reservation', 'accommodation_reservation'), ('event_reservation', 'event_reservation'), ('special_request', 'special_request')], default='accommodation_quote')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=51)),
                ('direccion', models.CharField(max_length=51)),
            ],
        ),
        migrations.CreateModel(
            name='Huespedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=51)),
                ('apellido', models.CharField(max_length=51)),
                ('email', models.CharField(max_length=51)),
                ('tipo_documento', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=101)),
                ('identificacion', models.CharField(max_length=21)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=16)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('habitacion', models.CharField(max_length=21)),
                ('adultos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=51)),
                ('apellido', models.CharField(max_length=51)),
                ('email', models.CharField(max_length=51)),
                ('contraseña', models.CharField(max_length=21)),
                ('nombreHotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.hoteles')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=201)),
                ('description', models.TextField(max_length=1001)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
