# Generated by Django 5.1.1 on 2024-11-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_reserva_menores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='adultos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='identificacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='menores',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
