# Generated by Django 5.1.1 on 2024-11-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_reserva_estado_reserva_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_habitacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
